name: "JHU"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  get_jhu:
    runs-on: ubuntu-20.04
    if: github.repository == 'epiforecasts/covid19-forecast-hub-europe'
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install requirements
      run: pip3 install pandas

    - name: JHU Truth
      run: python3 ./code/auto_download/jhu_download.py

    - name: Commit files
      env:
        AUTH: ${{ secrets.GITHUBTOKEN }}
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action - JHU"
        git add --all
        git commit -m "JHU - daily"
        git pull --rebase
        git push
        echo "pushed to github"

    - name: Create issue about failure
      if: failure() && github.event_name == 'workflow_dispatch'
      uses: JasonEtco/create-an-issue@v2.5.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/action-issue-template.md
