name: Validations (R)

on:
  workflow_dispatch:
  # pull_request_target:
  #   branches: main
  # paths:
  #   - 'data-processed/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install validation package
        run: |
          install.packages("remotes")
          remotes::install_github("epiforecasts/ForecastHubValidations")
        shell: Rscript {0}

      - name: Run validations
        with:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          v <- ForecastHubValidations::validate_pr(
              gh_repo = Sys.getenv("GITHUB_REPOSITORY"),
              pr_number = Sys.getenv("PR_NUMBER"),
              data-folder = "data-processed"
          )
          print(v)
          check_for_errors(v)
        shell: Rscript {0}
